/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    fontSize: {
      r12: ['12px', '18px'],
      r14: ['14px', '24px'],
      r16: ['16px', '26px'],
      r18: ['18px', '30px'],
      r20: ['20px', '36px'],
      title: ['32px', '58px'],
      logo: ['80px', '144px'],
    },
    colors: {
      titleActive: '#14142B',
      body: '#4E4B66',
      label: '#A0A3BD',
      placeholder: '#D9DBE9',
      line: '#EFF0F6',
      inputBackground: '#EFF0F6',
      background: '#F7F7FC',
      offWhite: '#FEFEFE',
      indigo: '#1D1D50',
      primary: '#FFA52D',
      primaryDark: '#FF832D',
      primaryLight: '#FFD89E',
      secondary: '#4CAB22',
      secondaryDark: '#166C12',
      secondaryLight: '#8BE264',
      success: '#34C759',
      successDark: '#00A028',
      successLight: '#DDFFE6',
      error: '#FF4343',
      errorDark: '#C60B00',
      errorLight: '#FFD1CF',
    },
    fontFamily: {
      logo: ['Montserrat', 'sans-serif'],
      body: ['Noto Sans KR', 'sans-serif'],
      community: ['IBM Plex Sans KR', 'sans-serif'],
    },
  },
  plugins: [],
};
