export const signinURL = '/api/user/auth/signin';
export const signupURL = '/api/user/auth/signup';
export const signoutURL = '/api/user/auth/signout';
export const getMyInfoURL = '/api/user/auth/me';
export const followingURL = '/api/user/following';
export const createChannelURL = '/api/channel';
export const joinChannelURL = (channelId) => `/api/channels/${channelId}`;
export const inviteChannelURL = (channelId) => `/api/channels/${channelId}/users`;
export const getChannelInfoURL = (channelId) => `/api/channels/${channelId}`;
export const exitChannelURL = (channelId) => `/api/channels/${channelId}/me`;
export const deleteChannelURL = (channelId) => `/api/channels/${channelId}`;
export const modifyChannelURL = (channelId) => `/api/channels/${channelId}/settings`;
export const updateLastReadURL = (channelId) => `/api/channels/${channelId}/lastRead`;
